spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/db_post?serverTimeZone=Asia/Seoul&useUniCode=true
    url: jdbc:mysql://localhost:3306/db_post?serverTimeZone=Asia/Seoul&useUniCode=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: jwt-secret-key-longer-than-32-characters-mzc-study-blog-be
  expiration: 86400000