spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/db_post?serverTimeZone=Asia/Seoul&useUniCode=true
    url: jdbc:mysql://localhost:3306/db_post?serverTimeZone=Asia/Seoul&useUniCode=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update